export const DICT = {
  uk: {
    navAbout:'Про фонд', navDirections:'Напрямки', navRegistry:'Реєстр', navGratitude:'Подяки', navRequisites:'Реквізити', navContacts:'Контакти',
    heroKicker:'Благодійний фонд • з 2022 року',
    heroTitle1:'Миколаїв', heroTitle2:'Нескорений',
    heroSub:'Підтримуємо Збройні Сили України та цивільне населення, яке постраждало від війни, — від перших днів повномасштабного вторгнення.',
    heroNote:'Разом наближаємо Перемогу України',
    heroChip1:'Вознесенськ, Миколаївська область',
    heroChip2:'Понад 140 одиниць техніки передано',
    aboutKicker:'Про фонд',
    aboutTitle:'Об\u2019єднані заради підтримки захисників і людей',
    aboutP1:'Благодійний фонд «Миколаїв Нескорений» розпочав діяльність у 2022 році з початком повномасштабного вторгнення. Від перших днів війни команда об\u2019єднала волонтерів, благодійників та небайдужих громадян задля підтримки військових і цивільних.',
    aboutP2:'Упродовж 2022\u20132026 років волонтери здійснювали гуманітарні місії до населених пунктів поблизу лінії фронту та деокупованих територій — на Миколаївському, Херсонському, Запорізькому й Донецькому напрямках.',
    missionLabel:'Наша місія',
    missionText:'Ми працюємо заради підтримки українських захисників та цивільного населення, яке постраждало від війни. Завдяки партнерам, волонтерам і благодійникам фонд продовжує забезпечувати військових технікою, обладнанням та гуманітарною допомогою.',
    dirKicker:'Напрямки', dirTitle:'Чим займається фонд',
    dirSub:'Чотири ключові напрямки, у яких ми працюємо щодня — від забезпечення підрозділів до соціальної підтримки громад.',
    resultsKicker:'Результати роботи', resultsTitle:'Що передано українській армії',
    resultsSub:'З початку повномасштабної війни силами фонду для потреб Збройних Сил України передано техніку, обладнання та гуманітарну допомогу.',
    grpTransport:'Транспорт і техніка', grpEquip:'Обладнання', grpHuman:'Гуманітарна допомога',
    frontsTitle:'Напрямки допомоги:',
    regKicker:'Реєстр допомоги', regTitle:'Кому ми допомогли',
    regSub:'Десятки військових частин ЗСУ, Національної гвардії та територіальної оборони отримали техніку, обладнання й гуманітарну допомогу. Нижче — частина переданого за офіційними зверненнями підрозділів.',
    regMore:'\u2026та десятки інших підрозділів за всіма напрямками фронту.',
    gratKicker:'Документи', gratTitle:'Подяки та запити',
    gratSub:'Уся допомога надається на підставі офіційних запитів військових частин. У відповідь підрозділи надсилають фонду подяки за підтримку.',
    reqLabel:'Офіційний запит', gratLabel:'Подяка від підрозділу',
    docReqCaption:'Запит на допомогу від військової частини А7356, м. Баштанка.',
    docGratCaption:'Подяка від військової частини А7053 за підтримку на Південному напрямку.',
    unitsLabel:'Військові частини, які зверталися до фонду:',
    gratStat:'90+', gratStatLabel:'офіційних запитів і подяк від військових частин',
    partnersTitle:'Партнери та підтримка',
    partnersText:'Діяльність фонду реалізується за підтримки партнерів, зокрема ДП НАЕК «Енергоатом» та ПрАТ «Юженергобуд», а також волонтерів і благодійників, які наближають спільну Перемогу.',
    contactsKicker:'Контакти', contactsTitle:'Зв\u2019яжіться з фондом',
    addrLabel:'Адреса', addr:'56501, Миколаївська область, м. Вознесенськ, вул. Соборності, 23/27',
    phoneLabel:'Телефон', edrpouLabel:'ЄДРПОУ', headLabel:'Керівник', head:'Дядюра Павло Сергійович',
    cardTitle:'Миколаїв Нескорений',
    cardSub:'Благодійна організація «Благодійний фонд «Миколаїв Нескорений»',
    footerName:'БФ «Миколаїв Нескорений»',
    footerRights:'© 2022\u20132026 Благодійний фонд «Миколаїв Нескорений». Усі права захищено.'
  },
  en: {
    navAbout:'About', navDirections:'What we do', navRegistry:'Registry', navGratitude:'Gratitude', navRequisites:'Details', navContacts:'Contacts',
    heroKicker:'Charity Fund \u2022 since 2022',
    heroTitle1:'Mykolaiv', heroTitle2:'Invictus',
    heroSub:'We support the Armed Forces of Ukraine and civilians affected by the war \u2014 from the very first days of the full-scale invasion.',
    heroNote:'Together we bring Ukraine\u2019s Victory closer',
    heroChip1:'Voznesensk, Mykolaiv region',
    heroChip2:'Over 140 vehicles delivered',
    aboutKicker:'About the fund',
    aboutTitle:'United to support defenders and people',
    aboutP1:'The \u00abMykolaiv Invictus\u00bb Charity Fund began its work in 2022 with the start of the full-scale invasion. From the first days of the war, the team united volunteers, benefactors and caring citizens to support the military and civilians.',
    aboutP2:'Throughout 2022\u20132026, volunteers carried out humanitarian missions to settlements near the front line and de-occupied territories \u2014 on the Mykolaiv, Kherson, Zaporizhzhia and Donetsk directions.',
    missionLabel:'Our mission',
    missionText:'We work to support Ukrainian defenders and civilians affected by the war. Thanks to partners, volunteers and benefactors, the fund continues to provide the military with vehicles, equipment and humanitarian aid.',
    dirKicker:'What we do', dirTitle:'How the fund operates',
    dirSub:'Four key areas we work in every day \u2014 from equipping units to social support for communities.',
    resultsKicker:'Our impact', resultsTitle:'Delivered to the Ukrainian army',
    resultsSub:'Since the start of the full-scale war, the fund has delivered vehicles, equipment and humanitarian aid for the needs of the Armed Forces of Ukraine.',
    grpTransport:'Vehicles & machinery', grpEquip:'Equipment', grpHuman:'Humanitarian aid',
    frontsTitle:'Areas covered:',
    regKicker:'Aid registry', regTitle:'Whom we helped',
    regSub:'Dozens of units of the Armed Forces, National Guard and territorial defence received vehicles, equipment and humanitarian aid. Below is part of what was delivered on the units\u2019 official requests.',
    regMore:'\u2026and dozens of other units across every front-line direction.',
    gratKicker:'Documents', gratTitle:'Gratitude & requests',
    gratSub:'All aid is provided on the basis of official requests from military units. In return, units send the fund letters of gratitude for the support.',
    reqLabel:'Official request', gratLabel:'Gratitude from a unit',
    docReqCaption:'Aid request from military unit A7356, Bashtanka.',
    docGratCaption:'Gratitude from military unit A7053 for support on the Southern direction.',
    unitsLabel:'Military units that addressed the fund:',
    gratStat:'90+', gratStatLabel:'official requests & letters of gratitude from units',
    partnersTitle:'Partners & support',
    partnersText:'The fund\u2019s work is carried out with the support of partners, including SE NNEGC \u00abEnergoatom\u00bb and PJSC \u00abYuzhenergobud\u00bb, as well as volunteers and benefactors who bring our shared Victory closer.',
    contactsKicker:'Contacts', contactsTitle:'Get in touch with the fund',
    addrLabel:'Address', addr:'56501, Mykolaiv region, Voznesensk, 23/27 Sobornosti St.',
    phoneLabel:'Phone', edrpouLabel:'EDRPOU', headLabel:'Director', head:'Pavlo Diadiura',
    cardTitle:'Mykolaiv Invictus',
    cardSub:'Charity organisation \u00abMykolaiv Invictus Charity Fund\u00bb',
    footerName:'CF \u00abMykolaiv Invictus\u00bb',
    footerRights:'© 2022\u20132026 \u00abMykolaiv Invictus\u00bb Charity Fund. All rights reserved.'
  }
}

export const DATA = {
  stats: {
    uk: [
      {num:'\u2248140', label:'одиниць техніки'},
      {num:'74',        label:'позашляховики та пікапи'},
      {num:'53',        label:'вантажні автомобілі'},
      {num:'12\u202f500+', label:'ковдр передано'},
      {num:'9',         label:'прально-душових комплексів'},
      {num:'20\u202fмлн+', label:'грн гуманітарної допомоги'}
    ],
    en: [
      {num:'\u2248140', label:'units of vehicles'},
      {num:'74',        label:'SUVs & pickups'},
      {num:'53',        label:'trucks'},
      {num:'12,500+',   label:'blankets delivered'},
      {num:'9',         label:'laundry-shower units'},
      {num:'20M+',      label:'UAH of humanitarian aid'}
    ]
  },
  directions: {
    uk: [
      {no:'01', title:'Допомога ЗСУ',           text:'Позашляховики, вантажівки, тепловізори, прилади нічного бачення, квадрокоптери DJI MAVIC, Starlink, генератори та амуніція для підрозділів.'},
      {no:'02', title:'Гуманітарні місії',       text:'Продукти, засоби гігієни, одяг, ковдри, медикаменти та будівельні матеріали для прифронтових і деокупованих громад.'},
      {no:'03', title:'Соціальна підтримка',     text:'Лікарні, дитячі реабілітаційні центри, геріатричні пансіонати, Миколаївський зоопарк та внутрішньо переміщені особи.'},
      {no:'04', title:'Транспорт і техніка',     text:'Близько 140 одиниць техніки передано підрозділам ЗСУ, Нацгвардії та територіальної оборони по всій лінії фронту.'}
    ],
    en: [
      {no:'01', title:'Support for the Armed Forces', text:'SUVs, trucks, thermal imagers, night-vision devices, DJI MAVIC drones, Starlink, generators and gear for military units.'},
      {no:'02', title:'Humanitarian missions',         text:'Food, hygiene products, clothing, blankets, medicines and building materials for frontline and de-occupied communities.'},
      {no:'03', title:'Social support',                text:'Hospitals, children\u2019s rehabilitation centres, geriatric care homes, the Mykolaiv Zoo and internally displaced people.'},
      {no:'04', title:'Vehicles & machinery',          text:'Around 140 units of vehicles delivered to the Armed Forces, National Guard and territorial defence along the front line.'}
    ]
  },
  deliverTransport: {
    uk: ['74 позашляховики та пікапи','53 вантажні автомобілі','6 мікроавтобусів','Пожежний автомобіль','Кран-маніпулятор','Екскаватор-навантажувач','2 напівпричепи','Контейнер на 40 футів'],
    en: ['74 SUVs & pickups','53 trucks','6 minibuses','Fire engine','Crane manipulator','Backhoe loader','2 semi-trailers','40-foot container']
  },
  deliverEquip: {
    uk: ['9 мобільних прально-душових комплексів','12\u202f500+ ковдр','Квадрокоптери DJI MAVIC','Тепловізори та ПНБ','Радіостанції та планшети','Генератори й зарядні станції','Сонячні панелі','Плитоноски та каски'],
    en: ['9 mobile laundry-shower units','12,500+ blankets','DJI MAVIC drones','Thermal & night-vision devices','Radios & tablets','Generators & power stations','Solar panels','Plate carriers & helmets']
  },
  deliverHuman: {
    uk: ['Продукти харчування','Засоби гігієни','Одяг та взуття','Медикаменти','Будівельні матеріали','Понад 20 млн грн допомоги'],
    en: ['Food supplies','Hygiene products','Clothing & footwear','Medicines','Building materials','Over UAH 20M of aid']
  },
  fronts: {
    uk: ['Миколаївський','Херсонський','Запорізький','Донецький'],
    en: ['Mykolaiv','Kherson','Zaporizhzhia','Donetsk']
  },
  registry: [
    {u:'А1619',pu:'Донецька обл.',             pe:'Donetsk reg.',             iu:'Повнопривідний пікап',                                                                                         ie:'4WD pickup'},
    {u:'А1736',pu:'—',                          pe:'—',                        iu:'Вантажний автомобіль',                                                                                         ie:'Cargo truck'},
    {u:'А2802',pu:'Миколаїв',                   pe:'Mykolaiv',                 iu:'Дизельний позашляховик, Starlink, ноутбук, MAVIC, АКБ ×4',                                                    ie:'Diesel SUV, Starlink, laptop, MAVIC, 4 batteries'},
    {u:'А5750',pu:'Очаків',                     pe:'Ochakiv',                  iu:'Позашляховик підвищеної прохідності',                                                                          ie:'High-clearance SUV'},
    {u:'А7356',pu:'Рота вогневої підтримки',    pe:'Fire-support company',     iu:'Повнопривідне авто, скоби на бліндажі, буржуйки, сонячна електростанція, гідробар\u2019єр',                  ie:'4WD vehicle, dugout brackets, stoves, solar station, waterproofing'},
    {u:'3066', pu:'Київ',                        pe:'Kyiv',                     iu:'Пікап 4×4',                                                                                                    ie:'4×4 pickup'},
    {u:'3039', pu:'Миколаїв',                    pe:'Mykolaiv',                 iu:'Будматеріали, канцелярія, електроавтомати, мішки',                                                             ie:'Building materials, stationery, breakers, sandbags'},
    {u:'А1008',pu:'Волинська обл.',              pe:'Volyn reg.',               iu:'Повнопривідні авто ×2',                                                                                        ie:'4WD vehicles ×2'},
    {u:'А0666',pu:'Чорноморське, Одеська обл.', pe:'Chornomorske, Odesa reg.', iu:'Позашляховик',                                                                                                 ie:'SUV'},
    {u:'3044', pu:'Південноукраїнськ',           pe:'Pivdennoukrainsk',         iu:'Вантажне авто',                                                                                                ie:'Cargo vehicle'},
    {u:'А1804',pu:'Очаків',                      pe:'Ochakiv',                  iu:'Автомобіль БУС, генератор',                                                                                    ie:'Van, generator'},
    {u:'А4267',pu:'10 ОГШБр · Бахмут, Соледар', pe:'10th Mtn Bde · Bakhmut',  iu:'Прилад нічного бачення',                                                                                       ie:'Night-vision device'},
    {u:'А7053',pu:'Бахмут · Херсон',             pe:'Bakhmut · Kherson',        iu:'Позашляховики ×3, вантажне авто',                                                                              ie:'SUVs ×3, cargo vehicle'},
    {u:'А4056',pu:'—',                           pe:'—',                        iu:'Вантажне авто, позашляховик',                                                                                  ie:'Cargo vehicle, SUV'},
    {u:'А7363',pu:'Генічеськ, Херсонська обл.',  pe:'Henichesk, Kherson reg.', iu:'Модуль радіоелектроніки ×2',                                                                                   ie:'Electronic-warfare modules ×2'},
    {u:'А1836',pu:'Херсонська обл.',             pe:'Kherson reg.',             iu:'Ковдри ×500, намети ×2',                                                                                       ie:'500 blankets, 2 tents'},
    {u:'А2120',pu:'Херсонська обл.',             pe:'Kherson reg.',             iu:'Квадрокоптери DJI MAVIC',                                                                                      ie:'DJI MAVIC drones'},
    {u:'А2183',pu:'Первомайськ',                  pe:'Pervomaisk',               iu:'Будматеріали, ремонт КПП',                                                                                    ie:'Building materials, checkpoint repair'},
    {u:'А2227',pu:'Первомайська артбригада',      pe:'Pervomaisk artillery bde', iu:'КАМАЗ, мобільний прально-душовий комплекс',                                                                   ie:'KamAZ truck, mobile laundry-shower unit'},
    {u:'А2558',pu:'Врадіївка',                   pe:'Vradiivka',                iu:'Мобільні пости ×4',                                                                                            ie:'Mobile posts ×4'},
    {u:'А3384',pu:'Полтава',                      pe:'Poltava',                  iu:'Дизельний позашляховик',                                                                                       ie:'Diesel SUV'},
    {u:'А3425',pu:'Сумська обл.',                pe:'Sumy reg.',                iu:'КАМАЗ, МПДК, стаціонарний планшет',                                                                            ie:'KamAZ, laundry-shower unit, tablet'},
    {u:'А0415',pu:'Семиполки, Київська обл.',    pe:'Semypolky, Kyiv reg.',     iu:'Легковий автомобіль для евакуації',                                                                           ie:'Evacuation vehicle'},
    {u:'А4030',pu:'Київська обл.',               pe:'Kyiv reg.',                iu:'Пожежний автомобіль',                                                                                          ie:'Fire engine'},
    {u:'А4220',pu:'Київська обл.',               pe:'Kyiv reg.',                iu:'Авто медслужби — евакуація поранених',                                                                        ie:'Medical evacuation vehicle'},
    {u:'А4350',pu:'Київська обл.',               pe:'Kyiv reg.',                iu:'Nissan Pickup',                                                                                                ie:'Nissan Pickup'},
    {u:'А4355',pu:'—',                           pe:'—',                        iu:'Дрони DJI MAVIC ×3',                                                                                           ie:'DJI MAVIC drones ×3'},
    {u:'А4576',pu:'Кропивницький · Сумська обл.',pe:'Kropyvnytskyi · Sumy reg.',iu:'Вантажне авто, розкладачки НАТО',                                                                            ie:'Cargo vehicle, NATO cots'},
    {u:'А1582',pu:'Миколаїв',                    pe:'Mykolaiv',                 iu:'Принтер, антенний аналізатор, ПЗ-радіо, відеокамери, відеореєстратор',                                       ie:'Printer, antenna analyzer, SDR, cameras, DVR'},
    {u:'А4717',pu:'Полтава',                      pe:'Poltava',                  iu:'МПДК на базі вантажівки ×3, душові комплекси',                                                                ie:'Truck-based laundry-shower units ×3, showers'},
    {u:'А4818',pu:'Миколаїв',                    pe:'Mykolaiv',                 iu:'Плитоноски Ukr Tac, MAVIC 3, інверторні генератори, тепловізор, ПНБ, бензопили ×5',                         ie:'Ukr Tac plate carriers, MAVIC 3, inverter generators, thermal imager, NVD, 5 chainsaws'},
    {u:'А5000',pu:'—',                           pe:'—',                        iu:'Авто з причепом, дизель-генератор',                                                                            ie:'Vehicle with trailer, diesel generator'},
    {u:'А7353',pu:'Вознесенський батальйон ТРО', pe:'Voznesensk TD battalion',  iu:'Nissan X-Trail',                                                                                               ie:'Nissan X-Trail'},
    {u:'А3719',pu:'—',                           pe:'—',                        iu:'Квадрокоптер DJI MAVIC 3T',                                                                                    ie:'DJI MAVIC 3T drone'},
    {u:'А3958',pu:'Глухів, Сумська обл.',        pe:'Hlukhiv, Sumy reg.',       iu:'Пікап, VW Transporter T5, ноутбуки ×4, тепловізори ×4, принтери ×2, прожектори ×4',                         ie:'Pickup, VW Transporter T5, 4 laptops, 4 thermal imagers, 2 printers, 4 floodlights'},
    {u:'А3199',pu:'Сумська обл.',                pe:'Sumy reg.',                iu:'Дрон DJI MAVIC 3T',                                                                                            ie:'DJI MAVIC 3T drone'},
    {u:'А4582',pu:'—',                           pe:'—',                        iu:'Повнопривідний позашляховик',                                                                                   ie:'4WD SUV'},
    {u:'А4689',pu:'Подільськ, Одеська обл.',     pe:'Podilsk, Odesa reg.',      iu:'Міношукачі, набір сапера, Starlink',                                                                           ie:'Mine detectors, sapper kit, Starlink'},
    {u:'А0989',pu:'Стрілецький батальйон',       pe:'Rifle battalion',           iu:'Дизельний пікап',                                                                                              ie:'Diesel pickup'},
    {u:'А0284',pu:'Донецька / Луганська обл.',   pe:'Donetsk / Luhansk reg.',   iu:'Дрон DJI Mavic 3T',                                                                                            ie:'DJI Mavic 3T drone'},
    {u:'А2062',pu:'—',                           pe:'—',                        iu:'Вантажне авто для перевезення техніки',                                                                        ie:'Cargo vehicle for equipment transport'},
    {u:'А2734',pu:'Вознесенськ',                 pe:'Voznesensk',                iu:'Зенітний прожектор — протидія БПЛА «Shahed»',                                                                  ie:'Anti-air searchlight vs \u00abShahed\u00bb UAVs'},
    {u:'Зоопарк',pu:'Соц. підтримка · Миколаїв',pe:'Social · Mykolaiv',        iu:'Корми для тварин: пшениця, насіння соняшника',                                                                 ie:'Animal feed: wheat, sunflower seeds'},
    {u:'ЦСПРД', pu:'Соц. підтримка · Південноукраїнськ',pe:'Social · Pivdennoukrainsk',iu:'Бензогенератор, конвектори для дітей',                                                               ie:'Generator, heaters for children'},
    {u:'Лікарня',pu:'Соц. підтримка · Миргород', pe:'Social · Myrhorod',       iu:'Ковдри ×700',                                                                                                  ie:'700 blankets'}
  ],
  unitCodes: ['А0281','А0284','А0334','А0666','А0998','А1008','А1080','А1478','А1619','А1736','А1804','А1836','А1962','А2062','А2120','А2183','А2227','А2258','А2558','А2734','А2802','А3039','А3199','А3384','А3425','А3958','А4015','А4030','А4220','А4267','А4350','А4355','А4576','А4582','А4689','А4699','А4717','А4718','А4772','А4794','А4818','А5000','А5051','А5750','А7052','А7053','А7096','А7294','А7314','А7353','А7356','А7358','А7363','А7382']
}
