export const GRAT_DOCS = [
  {preview:'/docs/previews/gratitude/doc-0-Подяка-1.webp',pdf:'/docs/gratitude/Подяка .pdf',type:'Подяка',unit:null},
  {preview:'/docs/previews/gratitude/doc-1-Подяка-1-1.webp',pdf:'/docs/gratitude/Подяка 1.pdf',type:'Подяка',unit:null},
  {preview:'/docs/previews/gratitude/doc-2-Подяка-2-1.webp',pdf:'/docs/gratitude/Подяка 2.pdf',type:'Подяка',unit:null},
  {preview:'/docs/previews/gratitude/doc-3-Подяка-3-1.webp',pdf:'/docs/gratitude/Подяка 3.pdf',type:'Подяка',unit:null},
  {preview:'/docs/previews/gratitude/doc-4-Подяка-1.webp',pdf:'/docs/gratitude/Подяка.pdf',type:'Подяка',unit:null},
]

export const REQ_DOCS = [
  {preview:'/docs/previews/requests/doc-0-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1, Лист до БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-1-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1.    Лист до БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-2-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1.   Лист до БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-3-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1.  Лист  до  БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-4-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1.  Лист до БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-А4267-5-1.webp',pdf:'/docs/requests/1. Акт до БФ А4267.pdf',type:'Акт',unit:'А4267'},
  {preview:'/docs/previews/requests/doc-А7358-6-1.webp',pdf:'/docs/requests/1. Акт до БФ А7358.pdf',type:'Акт',unit:'А7358'},
  {preview:'/docs/previews/requests/doc-7-1-Запит-до-БФ-1.webp',pdf:'/docs/requests/1. Запит    до БФ.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-8-1-Запит-До-БФ-к-Акту-1-1.webp',pdf:'/docs/requests/1. Запит До БФ к Акту   №1.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-9-1-Запит-До-БФ-к-Акту-2-1.webp',pdf:'/docs/requests/1. Запит До БФ к Акту №2.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-10-1-Запит-до-БФ-1.webp',pdf:'/docs/requests/1. Запит до  БФ.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-А3958-11-1.webp',pdf:'/docs/requests/1. Запит до БФ  А3958.pdf',type:'Запит',unit:'А3958'},
  {preview:'/docs/previews/requests/doc-А0284-12-1.webp',pdf:'/docs/requests/1. Запит до БФ А0284.pdf',type:'Запит',unit:'А0284'},
  {preview:'/docs/previews/requests/doc-А2062-13-1.webp',pdf:'/docs/requests/1. Запит до БФ А2062.pdf',type:'Запит',unit:'А2062'},
  {preview:'/docs/previews/requests/doc-А2258-14-1.webp',pdf:'/docs/requests/1. Запит до БФ А2258.pdf',type:'Запит',unit:'А2258'},
  {preview:'/docs/previews/requests/doc-А2734-15-1.webp',pdf:'/docs/requests/1. Запит до БФ А2734.pdf',type:'Запит',unit:'А2734'},
  {preview:'/docs/previews/requests/doc-А3039-16-1.webp',pdf:'/docs/requests/1. Запит до БФ А3039.pdf',type:'Запит',unit:'А3039'},
  {preview:'/docs/previews/requests/doc-А3199-17-1.webp',pdf:'/docs/requests/1. Запит до БФ А3199.pdf',type:'Запит',unit:'А3199'},
  {preview:'/docs/previews/requests/doc-А3425-18-1.webp',pdf:'/docs/requests/1. Запит до БФ А3425.pdf',type:'Запит',unit:'А3425'},
  {preview:'/docs/previews/requests/doc-А3958-19-1.webp',pdf:'/docs/requests/1. Запит до БФ А3958.pdf',type:'Запит',unit:'А3958'},
  {preview:'/docs/previews/requests/doc-А4576-20-1.webp',pdf:'/docs/requests/1. Запит до БФ А4576.pdf',type:'Запит',unit:'А4576'},
  {preview:'/docs/previews/requests/doc-А4582-21-1.webp',pdf:'/docs/requests/1. Запит до БФ А4582.pdf',type:'Запит',unit:'А4582'},
  {preview:'/docs/previews/requests/doc-А4689-22-1.webp',pdf:'/docs/requests/1. Запит до БФ А4689.pdf',type:'Запит',unit:'А4689'},
  {preview:'/docs/previews/requests/doc-А4699-23-1.webp',pdf:'/docs/requests/1. Запит до БФ А4699.pdf',type:'Запит',unit:'А4699'},
  {preview:'/docs/previews/requests/doc-А4794-24-1.webp',pdf:'/docs/requests/1. Запит до БФ А4794.pdf',type:'Запит',unit:'А4794'},
  {preview:'/docs/previews/requests/doc-А4818-25-1.webp',pdf:'/docs/requests/1. Запит до БФ А4818.pdf',type:'Запит',unit:'А4818'},
  {preview:'/docs/previews/requests/doc-А5000-26-1.webp',pdf:'/docs/requests/1. Запит до БФ А5000.pdf',type:'Запит',unit:'А5000'},
  {preview:'/docs/previews/requests/doc-А7353-27-1.webp',pdf:'/docs/requests/1. Запит до БФ А7353.pdf',type:'Запит',unit:'А7353'},
  {preview:'/docs/previews/requests/doc-28-1-Запит-до-БФ-к-Акту-3-1.webp',pdf:'/docs/requests/1. Запит до БФ к Акту №3.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-29-1-Запит-до-БФ-1.webp',pdf:'/docs/requests/1. Запит до БФ.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-А1478-30-1.webp',pdf:'/docs/requests/1. ЛИСТ ДО БФ А1478.pdf',type:'Лист',unit:'А1478'},
  {preview:'/docs/previews/requests/doc-31-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист  до  БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-32-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист  до БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-А2183-33-1.webp',pdf:'/docs/requests/1. Лист від ВЧ А2183 до БФ.pdf',type:'Лист',unit:'А2183'},
  {preview:'/docs/previews/requests/doc-34-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист до    БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-35-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист до   БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-А1836-36-1.webp',pdf:'/docs/requests/1. Лист до  БФ А1836.pdf',type:'Лист',unit:'А1836'},
  {preview:'/docs/previews/requests/doc-37-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист до  БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-А4582-38-1.webp',pdf:'/docs/requests/1. Лист до БФ   А4582.pdf',type:'Лист',unit:'А4582'},
  {preview:'/docs/previews/requests/doc-А4717-39-1.webp',pdf:'/docs/requests/1. Лист до БФ   А4717.PDF',type:'Лист',unit:'А4717'},
  {preview:'/docs/previews/requests/doc-А2802-40-1.webp',pdf:'/docs/requests/1. Лист до БФ  А2802.pdf',type:'Лист',unit:'А2802'},
  {preview:'/docs/previews/requests/doc-А5750-41-1.webp',pdf:'/docs/requests/1. Лист до БФ  А5750.pdf',type:'Лист',unit:'А5750'},
  {preview:'/docs/previews/requests/doc-А0281-42-1.webp',pdf:'/docs/requests/1. Лист до БФ А0281.pdf',type:'Лист',unit:'А0281'},
  {preview:'/docs/previews/requests/doc-А0334-43-1.webp',pdf:'/docs/requests/1. Лист до БФ А0334.pdf',type:'Лист',unit:'А0334'},
  {preview:'/docs/previews/requests/doc-А0998-44-1.webp',pdf:'/docs/requests/1. Лист до БФ А0998.pdf',type:'Лист',unit:'А0998'},
  {preview:'/docs/previews/requests/doc-А1008-45-1.webp',pdf:'/docs/requests/1. Лист до БФ А1008.pdf',type:'Лист',unit:'А1008'},
  {preview:'/docs/previews/requests/doc-А1080-46-1.webp',pdf:'/docs/requests/1. Лист до БФ А1080.pdf',type:'Лист',unit:'А1080'},
  {preview:'/docs/previews/requests/doc-А1619-47-1.webp',pdf:'/docs/requests/1. Лист до БФ А1619.pdf',type:'Лист',unit:'А1619'},
  {preview:'/docs/previews/requests/doc-А1736-48-1.webp',pdf:'/docs/requests/1. Лист до БФ А1736.pdf',type:'Лист',unit:'А1736'},
  {preview:'/docs/previews/requests/doc-А1804-49-1.webp',pdf:'/docs/requests/1. Лист до БФ А1804.pdf',type:'Лист',unit:'А1804'},
  {preview:'/docs/previews/requests/doc-А1836-50-1.webp',pdf:'/docs/requests/1. Лист до БФ А1836.pdf',type:'Лист',unit:'А1836'},
  {preview:'/docs/previews/requests/doc-А1962-51-1.webp',pdf:'/docs/requests/1. Лист до БФ А1962.pdf',type:'Лист',unit:'А1962'},
  {preview:'/docs/previews/requests/doc-А2120-52-1.webp',pdf:'/docs/requests/1. Лист до БФ А2120.pdf',type:'Лист',unit:'А2120'},
  {preview:'/docs/previews/requests/doc-А2183-53-1.webp',pdf:'/docs/requests/1. Лист до БФ А2183.pdf',type:'Лист',unit:'А2183'},
  {preview:'/docs/previews/requests/doc-А2227-54-1.webp',pdf:'/docs/requests/1. Лист до БФ А2227.pdf',type:'Лист',unit:'А2227'},
  {preview:'/docs/previews/requests/doc-А2258-55-1.webp',pdf:'/docs/requests/1. Лист до БФ А2258.pdf',type:'Лист',unit:'А2258'},
  {preview:'/docs/previews/requests/doc-А2558-56-1.webp',pdf:'/docs/requests/1. Лист до БФ А2558.pdf',type:'Лист',unit:'А2558'},
  {preview:'/docs/previews/requests/doc-А2802-57-1.webp',pdf:'/docs/requests/1. Лист до БФ А2802.pdf',type:'Лист',unit:'А2802'},
  {preview:'/docs/previews/requests/doc-А3199-58-1.webp',pdf:'/docs/requests/1. Лист до БФ А3199.pdf',type:'Лист',unit:'А3199'},
  {preview:'/docs/previews/requests/doc-А3384-59-1.webp',pdf:'/docs/requests/1. Лист до БФ А3384.pdf',type:'Лист',unit:'А3384'},
  {preview:'/docs/previews/requests/doc-А3425-60-1.webp',pdf:'/docs/requests/1. Лист до БФ А3425.pdf',type:'Лист',unit:'А3425'},
  {preview:'/docs/previews/requests/doc-А3958-61-1.webp',pdf:'/docs/requests/1. Лист до БФ А3958.pdf',type:'Лист',unit:'А3958'},
  {preview:'/docs/previews/requests/doc-А4015-62-1.webp',pdf:'/docs/requests/1. Лист до БФ А4015.pdf',type:'Лист',unit:'А4015'},
  {preview:'/docs/previews/requests/doc-А4030-63-1.webp',pdf:'/docs/requests/1. Лист до БФ А4030.pdf',type:'Лист',unit:'А4030'},
  {preview:'/docs/previews/requests/doc-А4220-64-1.webp',pdf:'/docs/requests/1. Лист до БФ А4220.pdf',type:'Лист',unit:'А4220'},
  {preview:'/docs/previews/requests/doc-А4350-65-1.webp',pdf:'/docs/requests/1. Лист до БФ А4350.pdf',type:'Лист',unit:'А4350'},
  {preview:'/docs/previews/requests/doc-А4355-66-1.webp',pdf:'/docs/requests/1. Лист до БФ А4355.pdf',type:'Лист',unit:'А4355'},
  {preview:'/docs/previews/requests/doc-А4576-67-1.webp',pdf:'/docs/requests/1. Лист до БФ А4576.pdf',type:'Лист',unit:'А4576'},
  {preview:'/docs/previews/requests/doc-А4689-68-1.webp',pdf:'/docs/requests/1. Лист до БФ А4689.pdf',type:'Лист',unit:'А4689'},
  {preview:'/docs/previews/requests/doc-А4717-69-1.webp',pdf:'/docs/requests/1. Лист до БФ А4717.PDF',type:'Лист',unit:'А4717'},
  {preview:'/docs/previews/requests/doc-А4718-70-1.webp',pdf:'/docs/requests/1. Лист до БФ А4718.pdf',type:'Лист',unit:'А4718'},
  {preview:'/docs/previews/requests/doc-А4772-71-1.webp',pdf:'/docs/requests/1. Лист до БФ А4772.pdf',type:'Лист',unit:'А4772'},
  {preview:'/docs/previews/requests/doc-А4818-72-1.webp',pdf:'/docs/requests/1. Лист до БФ А4818.pdf',type:'Лист',unit:'А4818'},
  {preview:'/docs/previews/requests/doc-А5051-73-1.webp',pdf:'/docs/requests/1. Лист до БФ А5051.pdf',type:'Лист',unit:'А5051'},
  {preview:'/docs/previews/requests/doc-А7052-74-1.webp',pdf:'/docs/requests/1. Лист до БФ А7052.pdf',type:'Лист',unit:'А7052'},
  {preview:'/docs/previews/requests/doc-А7053-75-1.webp',pdf:'/docs/requests/1. Лист до БФ А7053.pdf',type:'Лист',unit:'А7053'},
  {preview:'/docs/previews/requests/doc-А7096-76-1.webp',pdf:'/docs/requests/1. Лист до БФ А7096.pdf',type:'Лист',unit:'А7096'},
  {preview:'/docs/previews/requests/doc-А7294-77-1.webp',pdf:'/docs/requests/1. Лист до БФ А7294.pdf',type:'Лист',unit:'А7294'},
  {preview:'/docs/previews/requests/doc-А7314-78-1.webp',pdf:'/docs/requests/1. Лист до БФ А7314.pdf',type:'Лист',unit:'А7314'},
  {preview:'/docs/previews/requests/doc-А7353-79-1.webp',pdf:'/docs/requests/1. Лист до БФ А7353.pdf',type:'Лист',unit:'А7353'},
  {preview:'/docs/previews/requests/doc-А7382-80-1.webp',pdf:'/docs/requests/1. Лист до БФ А7382.pdf',type:'Лист',unit:'А7382'},
  {preview:'/docs/previews/requests/doc-В4056-81-1.webp',pdf:'/docs/requests/1. Лист до БФ В4056.pdf',type:'Лист',unit:'В4056'},
  {preview:'/docs/previews/requests/doc-82-1-Лист-до-БФ-Живогляд-1.webp',pdf:'/docs/requests/1. Лист до БФ Живогляд.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-83-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист до БФ,.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-84-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1. Лист до БФ..PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-85-1-Лист-запит-1.webp',pdf:'/docs/requests/1. Лист запит.pdf',type:'Запит',unit:null},
  {preview:'/docs/previews/requests/doc-А7363-86-1.webp',pdf:'/docs/requests/1. Лист ло БФ А7363.pdf',type:'Лист',unit:'А7363'},
  {preview:'/docs/previews/requests/doc-87-1-Лист-1.webp',pdf:'/docs/requests/1. Лист.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-88-1-Лист-до-БФ-1.webp',pdf:'/docs/requests/1.Лист до  БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-89-1-Лист-від-ВЧ-до-БФ-скан-копія.webp',pdf:'/docs/requests/1_Лист_від_ВЧ_до_БФ_скан_копія_тільки.jpg',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-90-photo-2026-06-23-16-37-49.webp',pdf:'/docs/requests/photo_2026-06-23_16-37-49.jpg',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-91-Лист-до-БФ-1.webp',pdf:'/docs/requests/Лист   до БФ.pdf',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-92-Лист-до-БФ-1.webp',pdf:'/docs/requests/Лист  до БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-93-Лист-до-БФ-1.webp',pdf:'/docs/requests/Лист до   БФ.PDF',type:'Лист',unit:null},
  {preview:'/docs/previews/requests/doc-А0666-94-1.webp',pdf:'/docs/requests/Лист до БФ А0666.pdf',type:'Лист',unit:'А0666'},
  {preview:'/docs/previews/requests/doc-95-Лист-до-БФ-1.webp',pdf:'/docs/requests/Лист до БФ.PDF',type:'Лист',unit:null},
]